[{"spell":"Aberto","type":"Charm","effect":"opens objects"},
{"spell":"Accio","type":"Charm","effect":"Summons an object"},
{"spell":"Age Line","type":"Enchantment","effect":"Hides things from younger people"},
{"spell":"Aguamenti","type":"Charm","effect":"shoots water from wand"},
{"spell":"Alarte Ascendare","type":"Spell","effect":"shoots things high in the air"},
{"spell":"Alohomora","type":"Charm","effect":"opens locked objects"},
{"spell":"Anapneo","type":"Spell","effect":"clears the target's airway"},
{"spell":"Anteoculatia","type":"Hex","effect":"turns head hair into antlers"},
{"spell":"Anti-Cheating","type":"Spell","effect":"prevents cheating on exams"},
{"spell":"Aparecium","type":"Spell","effect":"reveals invisible ink"},
{"spell":"Apparate","type":"Spell","effect":"teleportation spell"},
{"spell":"Arania Exumai","type":"Spell","effect":"blasts away spiders"},
{"spell":"Aqua Eructo","type":"Spell","effect":"shoots water from wand"},
{"spell":"Arresto Momentum","type":"Spell","effect":"slows down objects"},
{"spell":"Ascendio","type":"Spell","effect":"moves an object upward"},
{"spell":"Avada Kedavra","type":"Curse","effect":"murders opponent"},
{"spell":"Avifors","type":"Charm","effect":"turns small objects into birds"},
{"spell":"Avis","type":"Spell","effect":"launches birds from your wand"},
{"spell":"Babbling Curse ","type":"Curse","effect":"makes a person babble"},
{"spell":"Bombarda","type":"Spell","effect":"causes explosions"},
{"spell":"Bombarda Maxima","type":"Spell","effect":"causes large explosions"},
{"spell":"Bubble Head","type":"Charm","effect":"puts a person's head in a protective air bubble"},
{"spell":"Carpe Retractum","type":"Spell","effect":"shoots a rope from a wand to snag things"},
{"spell":"Caterwauling","type":"Charm","effect":"detects enemies and emits a scream"},
{"spell":"Cave Inimicum","type":"Charm","effect":"detects enemies and emits an alarm"},
{"spell":"Cheering","type":"Charm","effect":"makes a person happy and giddy"},
{"spell":"Cistem Aperio","type":"Spell","effect":"opens things"},
{"spell":"Colloportus","type":"Spell","effect":"locks doors"},
{"spell":"Colloshoo","type":"Spell","effect":"makes a person's shoes stick to the ground"},
{"spell":"Colovaria","type":"Charm","effect":"makes an object change colour"},
{"spell":"Confringo","type":"Curse","effect":"explode flames on target"},
{"spell":"Confundus","type":"Charm","effect":"used to confuse opponent"},
{"spell":"Conjunctivitis","type":"Curse","effect":"damages opponent's eyesight"},
{"spell":"Cornflake Skin","type":"Curse","effect":"gives a person cereal skin"},
{"spell":"Crucio","type":"Curse","effect":"tortures a person"},
{"spell":"Cushioning","type":"Charm","effect":"helps cushon a fall"},
{"spell":"Defodio","type":"Spell","effect":"dig out materials"},
{"spell":"Deletrius","type":"Spell","effect":"counters \"Prior Incantato\""},
{"spell":"Densaugeo","type":"Spell","effect":"enlarges teeth"},
{"spell":"Deprimo","type":"Spell","effect":"wind damaging spell"},
{"spell":"Depulso","type":"Charm","effect":"drives an object away"},
{"spell":"Descendo","type":"Spell","effect":"moves an object downwards"},
{"spell":"Diffindo","type":"Spell","effect":"splits seams"},
{"spell":"Diminuendo","type":"Spell","effect":"shrinks the target"},
{"spell":"Dissendium","type":"Spell","effect":"opens passageways"},
{"spell":"Disillusionment","type":"Charm","effect":"makes the target blend into the surroundings"},
{"spell":"Duro","type":"Spell","effect":"makes objects hard"},
{"spell":"Drought","type":"Charm","effect":"dries up puddles"},
{"spell":"Ears to Kumquats","type":"Spell","effect":"gives a person kumquat ears"},
{"spell":"Ear Shriveling ","type":"Curse","effect":"cause a person's ear to shrivel"},
{"spell":"Engorgio","type":"Charm","effect":"enlarges an item"},
{"spell":"Ennervate","type":"Spell","effect":"counters Stupefy"},
{"spell":"Entrail-Expelling","type":"Curse","effect":"expel entrails from a body"},
{"spell":"Episkey","type":"Spell","effect":"heals minor injuries"},
{"spell":"Epoximise","type":"Spell","effect":"binds objects together"},
{"spell":"Erecto","type":"Spell","effect":"builds things"},
{"spell":"Evanesco","type":"Spell","effect":"makes things vanish"},
{"spell":"Everte Statum","type":"Spell","effect":"throws a victim backwards"},
{"spell":"Expecto Patronum","type":"Charm","effect":"creates a Patronus"},
{"spell":"Expelliarmus","type":"Charm","effect":"disarms your opponent"},
{"spell":"Expulso","type":"Spell","effect":"makes objects explode"},
{"spell":"Extinguishing","type":"Spell","effect":"puts out fires"},
{"spell":"Ferula","type":"Spell","effect":"creates bandages"},
{"spell":"Fianto Duri","type":"Charm","effect":"defensive charm"},
{"spell":"Fidelius","type":"Charm","effect":"hides a secret within someone"},
{"spell":"Fiendfyre","type":"Curse","effect":"hard to control large fire curse"},
{"spell":"Finestra","type":"Spell","effect":"turns windows to dust"},
{"spell":"Finite","type":"Spell","effect":"finishes spell in the caster's area"},
{"spell":"Finite Incantatum","type":"Spell","effect":"stops any current spells"},
{"spell":"Flagrante","type":"Curse","effect":"multiplies and burns objects upon touch"},
{"spell":"Flagrate","type":"Spell","effect":"allows user to write on objects"},
{"spell":"Flame Freezing","type":"Charm","effect":"makes flames cool"},
{"spell":"Flipendo","type":"Jinx","effect":"knocks an object backwards"},
{"spell":"Flying","type":"Charm","effect":"makes objects fly"},
{"spell":"Fumos","type":"Spell","effect":"a defensive cloud of smoke"},
{"spell":"Furnunculus","type":"Curse","effect":"produces boils on opponent"},
{"spell":"Geminio","type":"Spell","effect":"duplicates an object"},
{"spell":"Glisseo","type":"Spell","effect":"turns stairs into ramps"},
{"spell":"Gripping","type":"Charm","effect":"makes it easier to hold things"},
{"spell":"Harmonia Nectere Passus","type":"Spell","effect":"mends broken things"},
{"spell":"Homenum Revelio","type":"Spell","effect":"reveals humans nearby"},
{"spell":"Homonculous","type":"Charm","effect":"lets a person track another's movement on a map"},
{"spell":"Homorphus","type":"Charm","effect":"Lockhart's warewolf \"cure\""},
{"spell":"Horcrux","type":"Curse","effect":"allows wizard to put their soul into an object"},
{"spell":"Illegibilus","type":"Spell","effect":"makes text unreadable"},
{"spell":"Immobulus","type":"Charm","effect":"renders target immobile"},
{"spell":"Impedimenta","type":"Charm","effect":"slows an advancing object"},
{"spell":"Imperio","type":"Curse","effect":"controls a person"},
{"spell":"Impervius","type":"Charm","effect":"makes an object repel water"},
{"spell":"Incarcerous","type":"Spell","effect":"ties someone up"},
{"spell":"Incendio","type":"Spell","effect":"starts a fire"},
{"spell":"Lacarnum Inflamarae","type":"Spell","effect":"shoots a fireball from caster's wand"},
{"spell":"Langlock","type":"Spell","effect":"glues opponent's tongue to roof of mouth"},
{"spell":"Legilimens","type":"Spell","effect":"allows caster to read the mind of the target"},
{"spell":"Levicorpus","type":"Spell","effect":"hangs target upside down by feet"},
{"spell":"Liberacorpus","type":"Spell","effect":"counter spell to Levicorpus"},
{"spell":"Locomotor Mortis","type":"Curse","effect":"locks opponent's legs"},
{"spell":"Lumos","type":"Spell","effect":"creates light at wand tip"},
{"spell":"Lumos Maxima","type":"Spell","effect":"creates ball of light that can brighten a room for a long period of time"},
{"spell":"Lumos Solem","type":"Spell","effect":"creates a strong beam of light from the wand"},
{"spell":"Meteolojinx Recanto","type":"Spell","effect":"causes weather effect spells to stop"},
{"spell":"Mimblewimble","type":"Curse","effect":"tongue ties it's target"},
{"spell":"Mobiliarbus","type":"Charm","effect":"moves objects with wand"},
{"spell":"Mobilicorpus","type":"Spell","effect":"moves unconcious bodies"},
{"spell":"Morsmorde","type":"Spell","effect":"conjures the dark mark"},
{"spell":"Morsmorde","type":"Spell","effect":"prevents nearby people from listening to conversations"},
{"spell":"Nox","type":"Spell","effect":"counter to Lumos, turns off light"},
{"spell":"Oculus Reparo","type":"Spell","effect":"repairs eyeglasses"},
{"spell":"Obliteration","type":"Charm","effect":"removes footprints"},
{"spell":"Obliviate","type":"Charm","effect":"erases memories"},
{"spell":"Obscuro","type":"Spell","effect":"blindfolds the victim"},
{"spell":"Oppugno","type":"Spell","effect":"makes conjured items attack"},
{"spell":"Orchideous","type":"Spell","effect":"conjures flowers"},
{"spell":"Periculum","type":"Spell","effect":"makes fireworks from the wand tip"},
{"spell":"Permanent Sticking","type":"Charm","effect":"causes items to permanently stick to things"},
{"spell":"Petrificus Totalus","type":"Spell","effect":"body bind"},
{"spell":"Piertotum Locomotor","type":"Spell","effect":"animates statues and suits of armor"},
{"spell":"Point Me","type":"Charm","effect":"wand acts like a compass"},
{"spell":"Portus","type":"Charm","effect":"makes an object a Portkey"},
{"spell":"Priori Incantatem","type":"Spell","effect":"when sibling wands duel, the weaker wand shows all recently cast spells"},
{"spell":"Prior Incantato","type":"Spell","effect":"reveals a wand's last spell"},
{"spell":"Protego","type":"Charm","effect":"cause spells to reflect back to the sender"},
{"spell":"Protego Totalum","type":"Charm","effect":"area protection charm"},
{"spell":"Quietus","type":"Spell","effect":"counter spell for Sonorous"},
{"spell":"Reducio","type":"Spell","effect":"returns items to original size. counters Engorgio"},
{"spell":"Reducto","type":"Spell","effect":"blasts solid objects aside"},
{"spell":"Relashio","type":"Spell","effect":"releases user from binding"},
{"spell":"Rennervate","type":"Spell","effect":"cures unconciousness"},
{"spell":"Reparo","type":"Spell","effect":"repairs things"},
{"spell":"Repello Muggletum","type":"Spell","effect":"keeps muggles away"},
{"spell":"Repello Inimicum","type":"Spell","effect":"keeps evil beings away"},
{"spell":"Revelio","type":"Spell","effect":"reveals hidden objects"},
{"spell":"Rictusempra","type":"Charm","effect":"tickles target"},
{"spell":"Riddikulus","type":"Spell","effect":"causes target to laugh and defeats Boggarts"},
{"spell":"Salvio Hexia","type":"Spell","effect":"protection against hexes"},
{"spell":"Scourgify","type":"Charm","effect":"cleaning charm"},
{"spell":"Sectumsempra","type":"Spell","effect":"causes wounds as if slashed by a sword"},
{"spell":"Serpensortia","type":"Spell","effect":"produces a snake"},
{"spell":"Silencio","type":"Spell","effect":"silences target"},
{"spell":"Slugulus Eructo","type":"Charm","effect":"makes target vomit slugs"},
{"spell":"Sonorus","type":"Spell","effect":"amplifies voice"},
{"spell":"Specialis Revelio","type":"Spell","effect":"reveals hidden secrets or magical properties"},
{"spell":"Stinging Jinx","type":"Jinx","effect":"makes target feel stinging"},
{"spell":"Stupefy","type":"Spell","effect":"knocks out target"},
{"spell":"Switching Spell","type":"Spell","effect":"switches objects"},
{"spell":"Tarantallegra","type":"Spell","effect":"forces target to dance"},
{"spell":"Tergeo","type":"Spell","effect":"cleans up messes"},
{"spell":"Unbreakable Vow","type":"Spell","effect":"a vow that if broken, kills you"},
{"spell":"Vulnera Sanentur","type":"Spell","effect":"heals target"},
{"spell":"Waddiwasi","type":"Spell","effect":"unsticks an object"},
{"spell":"Wingardium Leviosa","type":"Charm","effect":"makes an object fly"},
{"spell":"Wingardium Leviosa","type":"Charm","effect":"makes an object fly"}]