[{"name":"Aberto","category":"Charm","effect":"opens objects"},
{"name":"Accio","category":"Charm","effect":"Summons an object"},
{"name":"Age Line","category":"Enchantment","effect":"Hides things from younger people"},
{"name":"Aguamenti","category":"Charm","effect":"shoots water from wand"},
{"name":"Alarte Ascendare","category":"Spell","effect":"shoots things high in the air"},
{"name":"Alohomora","category":"Charm","effect":"opens locked objects"},
{"name":"Anapneo","category":"Spell","effect":"clears the target's airway"},
{"name":"Anteoculatia","category":"Hex","effect":"turns head hair into antlers"},
{"name":"Anti-Cheating","category":"Spell","effect":"prevents cheating on exams"},
{"name":"Aparecium","category":"Spell","effect":"reveals invisible ink"},
{"name":"Apparate","category":"Spell","effect":"teleportation name"},
{"name":"Arania Exumai","category":"Spell","effect":"blasts away spiders"},
{"name":"Aqua Eructo","category":"Spell","effect":"shoots water from wand"},
{"name":"Arresto Momentum","category":"Spell","effect":"slows down objects"},
{"name":"Ascendio","category":"Spell","effect":"moves an object upward"},
{"name":"Avada Kedavra","category":"Curse","effect":"murders opponent"},
{"name":"Avifors","category":"Charm","effect":"turns small objects into birds"},
{"name":"Avis","category":"Spell","effect":"launches birds from your wand"},
{"name":"Babbling Curse ","category":"Curse","effect":"makes a person babble"},
{"name":"Bombarda","category":"Spell","effect":"causes explosions"},
{"name":"Bombarda Maxima","category":"Spell","effect":"causes large explosions"},
{"name":"Bubble Head","category":"Charm","effect":"puts a person's head in a protective air bubble"},
{"name":"Carpe Retractum","category":"Spell","effect":"shoots a rope from a wand to snag things"},
{"name":"Caterwauling","category":"Charm","effect":"detects enemies and emits a scream"},
{"name":"Cave Inimicum","category":"Charm","effect":"detects enemies and emits an alarm"},
{"name":"Cheering","category":"Charm","effect":"makes a person happy and giddy"},
{"name":"Cistem Aperio","category":"Spell","effect":"opens things"},
{"name":"Colloportus","category":"Spell","effect":"locks doors"},
{"name":"Colloshoo","category":"Spell","effect":"makes a person's shoes stick to the ground"},
{"name":"Colovaria","category":"Charm","effect":"makes an object change colour"},
{"name":"Confringo","category":"Curse","effect":"explode flames on target"},
{"name":"Confundus","category":"Charm","effect":"used to confuse opponent"},
{"name":"Conjunctivitis","category":"Curse","effect":"damages opponent's eyesight"},
{"name":"Cornflake Skin","category":"Curse","effect":"gives a person cereal skin"},
{"name":"Crucio","category":"Curse","effect":"tortures a person"},
{"name":"Cushioning","category":"Charm","effect":"helps cushon a fall"},
{"name":"Defodio","category":"Spell","effect":"dig out materials"},
{"name":"Deletrius","category":"Spell","effect":"counters \"Prior Incantato\""},
{"name":"Densaugeo","category":"Spell","effect":"enlarges teeth"},
{"name":"Deprimo","category":"Spell","effect":"wind damaging name"},
{"name":"Depulso","category":"Charm","effect":"drives an object away"},
{"name":"Descendo","category":"Spell","effect":"moves an object downwards"},
{"name":"Diffindo","category":"Spell","effect":"splits seams"},
{"name":"Diminuendo","category":"Spell","effect":"shrinks the target"},
{"name":"Dissendium","category":"Spell","effect":"opens passageways"},
{"name":"Disillusionment","category":"Charm","effect":"makes the target blend into the surroundings"},
{"name":"Duro","category":"Spell","effect":"makes objects hard"},
{"name":"Drought","category":"Charm","effect":"dries up puddles"},
{"name":"Ears to Kumquats","category":"Spell","effect":"gives a person kumquat ears"},
{"name":"Ear Shriveling ","category":"Curse","effect":"cause a person's ear to shrivel"},
{"name":"Engorgio","category":"Charm","effect":"enlarges an item"},
{"name":"Ennervate","category":"Spell","effect":"counters Stupefy"},
{"name":"Entrail-Expelling","category":"Curse","effect":"expel entrails from a body"},
{"name":"Episkey","category":"Spell","effect":"heals minor injuries"},
{"name":"Epoximise","category":"Spell","effect":"binds objects together"},
{"name":"Erecto","category":"Spell","effect":"builds things"},
{"name":"Evanesco","category":"Spell","effect":"makes things vanish"},
{"name":"Everte Statum","category":"Spell","effect":"throws a victim backwards"},
{"name":"Expecto Patronum","category":"Charm","effect":"creates a Patronus"},
{"name":"Expelliarmus","category":"Charm","effect":"disarms your opponent"},
{"name":"Expulso","category":"Spell","effect":"makes objects explode"},
{"name":"Extinguishing","category":"Spell","effect":"puts out fires"},
{"name":"Ferula","category":"Spell","effect":"creates bandages"},
{"name":"Fianto Duri","category":"Charm","effect":"defensive charm"},
{"name":"Fidelius","category":"Charm","effect":"hides a secret within someone"},
{"name":"Fiendfyre","category":"Curse","effect":"hard to control large fire curse"},
{"name":"Finestra","category":"Spell","effect":"turns windows to dust"},
{"name":"Finite","category":"Spell","effect":"finishes name in the caster's area"},
{"name":"Finite Incantatum","category":"Spell","effect":"stops any current names"},
{"name":"Flagrante","category":"Curse","effect":"multiplies and burns objects upon touch"},
{"name":"Flagrate","category":"Spell","effect":"allows user to write on objects"},
{"name":"Flame Freezing","category":"Charm","effect":"makes flames cool"},
{"name":"Flipendo","category":"Jinx","effect":"knocks an object backwards"},
{"name":"Flying","category":"Charm","effect":"makes objects fly"},
{"name":"Fumos","category":"Spell","effect":"a defensive cloud of smoke"},
{"name":"Furnunculus","category":"Curse","effect":"produces boils on opponent"},
{"name":"Geminio","category":"Spell","effect":"duplicates an object"},
{"name":"Glisseo","category":"Spell","effect":"turns stairs into ramps"},
{"name":"Gripping","category":"Charm","effect":"makes it easier to hold things"},
{"name":"Harmonia Nectere Passus","category":"Spell","effect":"mends broken things"},
{"name":"Homenum Revelio","category":"Spell","effect":"reveals humans nearby"},
{"name":"Homonculous","category":"Charm","effect":"lets a person track another's movement on a map"},
{"name":"Homorphus","category":"Charm","effect":"Lockhart's warewolf \"cure\""},
{"name":"Horcrux","category":"Curse","effect":"allows wizard to put their soul into an object"},
{"name":"Illegibilus","category":"Spell","effect":"makes text unreadable"},
{"name":"Immobulus","category":"Charm","effect":"renders target immobile"},
{"name":"Impedimenta","category":"Charm","effect":"slows an advancing object"},
{"name":"Imperio","category":"Curse","effect":"controls a person"},
{"name":"Impervius","category":"Charm","effect":"makes an object repel water"},
{"name":"Incarcerous","category":"Spell","effect":"ties someone up"},
{"name":"Incendio","category":"Spell","effect":"starts a fire"},
{"name":"Lacarnum Inflamarae","category":"Spell","effect":"shoots a fireball from caster's wand"},
{"name":"Langlock","category":"Spell","effect":"glues opponent's tongue to roof of mouth"},
{"name":"Legilimens","category":"Spell","effect":"allows caster to read the mind of the target"},
{"name":"Levicorpus","category":"Spell","effect":"hangs target upside down by feet"},
{"name":"Liberacorpus","category":"Spell","effect":"counter name to Levicorpus"},
{"name":"Locomotor Mortis","category":"Curse","effect":"locks opponent's legs"},
{"name":"Lumos","category":"Spell","effect":"creates light at wand tip"},
{"name":"Lumos Maxima","category":"Spell","effect":"creates ball of light that can brighten a room for a long period of time"},
{"name":"Lumos Solem","category":"Spell","effect":"creates a strong beam of light from the wand"},
{"name":"Meteolojinx Recanto","category":"Spell","effect":"causes weather effect names to stop"},
{"name":"Mimblewimble","category":"Curse","effect":"tongue ties it's target"},
{"name":"Mobiliarbus","category":"Charm","effect":"moves objects with wand"},
{"name":"Mobilicorpus","category":"Spell","effect":"moves unconcious bodies"},
{"name":"Morsmorde","category":"Spell","effect":"conjures the dark mark"},
{"name":"Morsmorde","category":"Spell","effect":"prevents nearby people from listening to conversations"},
{"name":"Nox","category":"Spell","effect":"counter to Lumos, turns off light"},
{"name":"Oculus Reparo","category":"Spell","effect":"repairs eyeglasses"},
{"name":"Obliteration","category":"Charm","effect":"removes footprints"},
{"name":"Obliviate","category":"Charm","effect":"erases memories"},
{"name":"Obscuro","category":"Spell","effect":"blindfolds the victim"},
{"name":"Oppugno","category":"Spell","effect":"makes conjured items attack"},
{"name":"Orchideous","category":"Spell","effect":"conjures flowers"},
{"name":"Periculum","category":"Spell","effect":"makes fireworks from the wand tip"},
{"name":"Permanent Sticking","category":"Charm","effect":"causes items to permanently stick to things"},
{"name":"Petrificus Totalus","category":"Spell","effect":"body bind"},
{"name":"Piertotum Locomotor","category":"Spell","effect":"animates statues and suits of armor"},
{"name":"Point Me","category":"Charm","effect":"wand acts like a compass"},
{"name":"Portus","category":"Charm","effect":"makes an object a Portkey"},
{"name":"Priori Incantatem","category":"Spell","effect":"when sibling wands duel, the weaker wand shows all recently cast names"},
{"name":"Prior Incantato","category":"Spell","effect":"reveals a wand's last name"},
{"name":"Protego","category":"Charm","effect":"cause names to reflect back to the sender"},
{"name":"Protego Totalum","category":"Charm","effect":"area protection charm"},
{"name":"Quietus","category":"Spell","effect":"counter name for Sonorous"},
{"name":"Reducio","category":"Spell","effect":"returns items to original size. counters Engorgio"},
{"name":"Reducto","category":"Spell","effect":"blasts solid objects aside"},
{"name":"Relashio","category":"Spell","effect":"releases user from binding"},
{"name":"Rennervate","category":"Spell","effect":"cures unconciousness"},
{"name":"Reparo","category":"Spell","effect":"repairs things"},
{"name":"Repello Muggletum","category":"Spell","effect":"keeps muggles away"},
{"name":"Repello Inimicum","category":"Spell","effect":"keeps evil beings away"},
{"name":"Revelio","category":"Spell","effect":"reveals hidden objects"},
{"name":"Rictusempra","category":"Charm","effect":"tickles target"},
{"name":"Riddikulus","category":"Spell","effect":"causes target to laugh and defeats Boggarts"},
{"name":"Salvio Hexia","category":"Spell","effect":"protection against hexes"},
{"name":"Scourgify","category":"Charm","effect":"cleaning charm"},
{"name":"Sectumsempra","category":"Spell","effect":"causes wounds as if slashed by a sword"},
{"name":"Serpensortia","category":"Spell","effect":"produces a snake"},
{"name":"Silencio","category":"Spell","effect":"silences target"},
{"name":"Slugulus Eructo","category":"Charm","effect":"makes target vomit slugs"},
{"name":"Sonorus","category":"Spell","effect":"amplifies voice"},
{"name":"Specialis Revelio","category":"Spell","effect":"reveals hidden secrets or magical properties"},
{"name":"Stinging Jinx","category":"Jinx","effect":"makes target feel stinging"},
{"name":"Stupefy","category":"Spell","effect":"knocks out target"},
{"name":"Switching name","category":"Spell","effect":"switches objects"},
{"name":"Tarantallegra","category":"Spell","effect":"forces target to dance"},
{"name":"Tergeo","category":"Spell","effect":"cleans up messes"},
{"name":"Unbreakable Vow","category":"Spell","effect":"a vow that if broken, kills you"},
{"name":"Vulnera Sanentur","category":"Spell","effect":"heals target"},
{"name":"Waddiwasi","category":"Spell","effect":"unsticks an object"},
{"name":"Wingardium Leviosa","category":"Charm","effect":"makes an object fly"},
{"name":"Wingardium Leviosa","category":"Charm","effect":"makes an object fly"}]
