[{"name":"Aberto","category":"Charm","effect":"Opens objects"},
{"name":"Accio","category":"Charm","effect":"Summons an object"},
{"name":"Age Line","category":"Enchantment","effect":"Hides things from younger people"},
{"name":"Aguamenti","category":"Charm","effect":"Shoots water from wand"},
{"name":"Alarte Ascendare","category":"Spell","effect":"Shoots things high in the air"},
{"name":"Alohomora","category":"Charm","effect":"Opens locked objects"},
{"name":"Anapneo","category":"Spell","effect":"Clears the target's airway"},
{"name":"Anteoculatia","category":"Hex","effect":"Turns head hair into antlers"},
{"name":"Anti-Cheating","category":"Spell","effect":"prevents cheating on exams"},
{"name":"Aparecium","category":"Spell","effect":"Reveals invisible ink"},
{"name":"Apparate","category":"Spell","effect":"Teleportation spell"},
{"name":"Arania Exumai","category":"Spell","effect":"Blasts away spiders"},
{"name":"Aqua Eructo","category":"Spell","effect":"Shoots water from wand"},
{"name":"Arresto Momentum","category":"Spell","effect":"Slows down objects"},
{"name":"Ascendio","category":"Spell","effect":"Moves an object upward"},
{"name":"Avada Kedavra","category":"Curse","effect":"Murders opponent"},
{"name":"Avifors","category":"Charm","effect":"Turns small objects into birds"},
{"name":"Avis","category":"Spell","effect":"Launches birds from your wand"},
{"name":"Babbling Curse ","category":"Curse","effect":"Makes a person babble"},
{"name":"Bombarda","category":"Spell","effect":"Causes explosions"},
{"name":"Bombarda Maxima","category":"Spell","effect":"Causes large explosions"},
{"name":"Bubble Head","category":"Charm","effect":"Puts a person's head in a protective air bubble"},
{"name":"Carpe Retractum","category":"Spell","effect":"Shoots a rope from a wand to snag things"},
{"name":"Caterwauling","category":"Charm","effect":"Detects enemies and emits a scream"},
{"name":"Cave Inimicum","category":"Charm","effect":"Detects enemies and emits an alarm"},
{"name":"Cheering","category":"Charm","effect":"Makes a person happy and giddy"},
{"name":"Cistem Aperio","category":"Spell","effect":"Opens things"},
{"name":"Colloportus","category":"Spell","effect":"Locks doors"},
{"name":"Colloshoo","category":"Spell","effect":"Makes a person's shoes stick to the ground"},
{"name":"Colovaria","category":"Charm","effect":"Makes an object change colour"},
{"name":"Confringo","category":"Curse","effect":"Explode flames on target"},
{"name":"Confundus","category":"Charm","effect":"Used to confuse opponent"},
{"name":"Conjunctivitis","category":"Curse","effect":"Damages opponent's eyesight"},
{"name":"Cornflake Skin","category":"Curse","effect":"Gives a person cereal skin"},
{"name":"Crucio","category":"Curse","effect":"Tortures a person"},
{"name":"Cushioning","category":"Charm","effect":"Helps cushon a fall"},
{"name":"Defodio","category":"Spell","effect":"Dig out materials"},
{"name":"Deletrius","category":"Spell","effect":"Counters \"Prior Incantato\""},
{"name":"Densaugeo","category":"Spell","effect":"Enlarges teeth"},
{"name":"Deprimo","category":"Spell","effect":"Wind damaging spell"},
{"name":"Depulso","category":"Charm","effect":"Drives an object away"},
{"name":"Descendo","category":"Spell","effect":"Moves an object downwards"},
{"name":"Diffindo","category":"Spell","effect":"Splits seams"},
{"name":"Diminuendo","category":"Spell","effect":"Shrinks the target"},
{"name":"Dissendium","category":"Spell","effect":"Opens passageways"},
{"name":"Disillusionment","category":"Charm","effect":"Makes the target blend into the surroundings"},
{"name":"Duro","category":"Spell","effect":"Makes objects hard"},
{"name":"Drought","category":"Charm","effect":"Dries up puddles"},
{"name":"Ears to Kumquats","category":"Spell","effect":"Gives a person kumquat ears"},
{"name":"Ear Shriveling ","category":"Curse","effect":"Cause a person's ear to shrivel"},
{"name":"Engorgio","category":"Charm","effect":"Enlarges an item"},
{"name":"Ennervate","category":"Spell","effect":"Counters Stupefy"},
{"name":"Entrail-Expelling","category":"Curse","effect":"Expel entrails from a body"},
{"name":"Episkey","category":"Spell","effect":"Heals minor injuries"},
{"name":"Epoximise","category":"Spell","effect":"Binds objects together"},
{"name":"Erecto","category":"Spell","effect":"Builds things"},
{"name":"Evanesco","category":"Spell","effect":"Makes things vanish"},
{"name":"Everte Statum","category":"Spell","effect":"Throws a victim backwards"},
{"name":"Expecto Patronum","category":"Charm","effect":"Creates a Patronus"},
{"name":"Expelliarmus","category":"Charm","effect":"Disarms your opponent"},
{"name":"Expulso","category":"Spell","effect":"Makes objects explode"},
{"name":"Extinguishing","category":"Spell","effect":"Puts out fires"},
{"name":"Ferula","category":"Spell","effect":"Creates bandages"},
{"name":"Fianto Duri","category":"Charm","effect":"Defensive charm"},
{"name":"Fidelius","category":"Charm","effect":"Hides a secret within someone"},
{"name":"Fiendfyre","category":"Curse","effect":"Hard to control large fire curse"},
{"name":"Finestra","category":"Spell","effect":"Turns windows to dust"},
{"name":"Finite","category":"Spell","effect":"Finishes spell in the caster's area"},
{"name":"Finite Incantatum","category":"Spell","effect":"Stops any current spells"},
{"name":"Flagrante","category":"Curse","effect":"Multiplies and burns objects upon touch"},
{"name":"Flagrate","category":"Spell","effect":"Allows user to write on objects"},
{"name":"Flame Freezing","category":"Charm","effect":"Makes flames cool"},
{"name":"Flipendo","category":"Jinx","effect":"Knocks an object backwards"},
{"name":"Flying","category":"Charm","effect":"Makes objects fly"},
{"name":"Fumos","category":"Spell","effect":"A defensive cloud of smoke"},
{"name":"Furnunculus","category":"Curse","effect":"Produces boils on opponent"},
{"name":"Geminio","category":"Spell","effect":"Duplicates an object"},
{"name":"Glisseo","category":"Spell","effect":"Turns stairs into ramps"},
{"name":"Gripping","category":"Charm","effect":"Makes it easier to hold things"},
{"name":"Harmonia Nectere Passus","category":"Spell","effect":"Mends broken things"},
{"name":"Homenum Revelio","category":"Spell","effect":"Reveals humans nearby"},
{"name":"Homonculous","category":"Charm","effect":"Lets a person track another's movement on a map"},
{"name":"Homorphus","category":"Charm","effect":"Lockhart's warewolf \"cure\""},
{"name":"Horcrux","category":"Curse","effect":"Allows wizard to put their soul into an object"},
{"name":"Illegibilus","category":"Spell","effect":"Makes text unreadable"},
{"name":"Immobulus","category":"Charm","effect":"Renders target immobile"},
{"name":"Impedimenta","category":"Charm","effect":"Slows an advancing object"},
{"name":"Imperio","category":"Curse","effect":"Controls a person"},
{"name":"Impervius","category":"Charm","effect":"Makes an object repel water"},
{"name":"Incarcerous","category":"Spell","effect":"Ties someone up"},
{"name":"Incendio","category":"Spell","effect":"Starts a fire"},
{"name":"Lacarnum Inflamarae","category":"Spell","effect":"Shoots a fireball from caster's wand"},
{"name":"Langlock","category":"Spell","effect":"Glues opponent's tongue to roof of mouth"},
{"name":"Legilimens","category":"Spell","effect":"Allows caster to read the mind of the target"},
{"name":"Levicorpus","category":"Spell","effect":"Hangs target upside down by feet"},
{"name":"Liberacorpus","category":"Spell","effect":"Counter spell to Levicorpus"},
{"name":"Locomotor Mortis","category":"Curse","effect":"Locks opponent's legs"},
{"name":"Lumos","category":"Spell","effect":"Creates light at wand tip"},
{"name":"Lumos Maxima","category":"Spell","effect":"Creates ball of light that can brighten a room for a long period of time"},
{"name":"Lumos Solem","category":"Spell","effect":"Creates a strong beam of light from the wand"},
{"name":"Meteolojinx Recanto","category":"Spell","effect":"Causes weather effect spells to stop"},
{"name":"Mimblewimble","category":"Curse","effect":"Tongue ties it's target"},
{"name":"Mobiliarbus","category":"Charm","effect":"Moves objects with wand"},
{"name":"Mobilicorpus","category":"Spell","effect":"Moves unconcious bodies"},
{"name":"Morsmorde","category":"Spell","effect":"Conjures the dark mark"},
{"name":"Morsmorde","category":"Spell","effect":"Prevents nearby people from listening to conversations"},
{"name":"Nox","category":"Spell","effect":"Counter to Lumos, turns off light"},
{"name":"Oculus Reparo","category":"Spell","effect":"Repairs eyeglasses"},
{"name":"Obliteration","category":"Charm","effect":"Removes footprints"},
{"name":"Obliviate","category":"Charm","effect":"Erases memories"},
{"name":"Obscuro","category":"Spell","effect":"Blindfolds the victim"},
{"name":"Oppugno","category":"Spell","effect":"Makes conjured items attack"},
{"name":"Orchideous","category":"Spell","effect":"Conjures flowers"},
{"name":"Periculum","category":"Spell","effect":"Makes fireworks from the wand tip"},
{"name":"Permanent Sticking","category":"Charm","effect":"Causes items to permanently stick to things"},
{"name":"Petrificus Totalus","category":"Spell","effect":"Body bind"},
{"name":"Piertotum Locomotor","category":"Spell","effect":"Animates statues and suits of armor"},
{"name":"Point Me","category":"Charm","effect":"Wand acts like a compass"},
{"name":"Portus","category":"Charm","effect":"Makes an object a Portkey"},
{"name":"Priori Incantatem","category":"Spell","effect":"When sibling wands duel, the weaker wand shows all recently cast names"},
{"name":"Prior Incantato","category":"Spell","effect":"Reveals a wand's last spell"},
{"name":"Protego","category":"Charm","effect":"Cause spells to reflect back to the sender"},
{"name":"Protego Totalum","category":"Charm","effect":"Area protection charm"},
{"name":"Quietus","category":"Spell","effect":"Counter spell for Sonorous"},
{"name":"Reducio","category":"Spell","effect":"Returns items to original size. counters Engorgio"},
{"name":"Reducto","category":"Spell","effect":"Blasts solid objects aside"},
{"name":"Relashio","category":"Spell","effect":"Releases user from binding"},
{"name":"Rennervate","category":"Spell","effect":"Cures unconciousness"},
{"name":"Reparo","category":"Spell","effect":"Repairs things"},
{"name":"Repello Muggletum","category":"Spell","effect":"Keeps muggles away"},
{"name":"Repello Inimicum","category":"Spell","effect":"Keeps evil beings away"},
{"name":"Revelio","category":"Spell","effect":"Reveals hidden objects"},
{"name":"Rictusempra","category":"Charm","effect":"Tickles target"},
{"name":"Riddikulus","category":"Spell","effect":"Causes target to laugh and defeats Boggarts"},
{"name":"Salvio Hexia","category":"Spell","effect":"Protection against hexes"},
{"name":"Scourgify","category":"Charm","effect":"Cleaning charm"},
{"name":"Sectumsempra","category":"Spell","effect":"Causes wounds as if slashed by a sword"},
{"name":"Serpensortia","category":"Spell","effect":"Produces a snake"},
{"name":"Silencio","category":"Spell","effect":"Silences target"},
{"name":"Slugulus Eructo","category":"Charm","effect":"Makes target vomit slugs"},
{"name":"Sonorus","category":"Spell","effect":"Amplifies voice"},
{"name":"Specialis Revelio","category":"Spell","effect":"Reveals hidden secrets or magical properties"},
{"name":"Stinging Jinx","category":"Jinx","effect":"Makes target feel stinging"},
{"name":"Stupefy","category":"Spell","effect":"Knocks out target"},
{"name":"Switching","category":"Spell","effect":"Switches objects"},
{"name":"Tarantallegra","category":"Spell","effect":"Forces target to dance"},
{"name":"Tergeo","category":"Spell","effect":"Cleans up messes"},
{"name":"Unbreakable Vow","category":"Spell","effect":"A vow that if broken, kills you"},
{"name":"Vulnera Sanentur","category":"Spell","effect":"Heals target"},
{"name":"Waddiwasi","category":"Spell","effect":"Unsticks an object"},
{"name":"Wingardium Leviosa","category":"Charm","effect":"Makes an object fly"}]
