{
  "Cores": [
    "Phoenix Feather",
    "Unicorn Tail Hair",
    "Dragon Heartstring",
    "Thestra Hair",
    "Troll Whisker",
    "Rainbow Coral",
    "Basilisk Horn",
    "Minotaur Bone",
    "Mermaid Hair",
    "Spider Fang"
  ],
  "Wood": [
    "Acacia",
    "Alder",
    "Ash",
    "Aspen",
    "Beech",
    "Blackthorn",
    "Cedar",
    "Cherry",
    "Chestnut",
    "Cypress",
    "Dogwood",
    "Ebony",
    "Elder",
    "Elm",
    "Fir",
    "Hawthorn",
    "Hazel",
    "Holly",
    "Larch",
    "Laurel",
    "Maple",
    "Mohagany",
    "Pine",
    "Poplar",
    "Oak",
    "Redwood",
    "Rowan",
    "Silver Lime",
    "Spruce",
    "Sycamore",
    "Vine",
    "Walnut",
    "Willow",
  ]
}